TestNG Homework
nmyshko/Test2 pull request #1
Opened 2022-12-06 10:25 UTC by nmyshko

2022-12-06 10:54 UTC, wildpioneer requested changes

2022-12-06 10:54 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivision.java
> +        if(Double.POSITIVE_INFINITY == c / 0) {
Это ты схитрила. Никаких if-ов в методе быть не должно.

2022-12-06 10:54 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivisionTest.java
> +    }@Test(priority = 5, groups = "divDouble", invocationCount = 2, invocationTimeOut = 5)
Форматирование должно быть единым по всему проекту
Меню Code -> Reformat Code

2022-12-06 10:54 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivisionTest.java
> +        Assert.assertEquals(calculator.divDouble(10.0, 0), 6, "Неверное значение!"); // не понимаю как тест сделать успешным
https://www.baeldung.com/java-division-by-zero

2022-12-13 10:20 UTC, wildpioneer commented on src/test/java/tests/CalculatorDivisionTest.java
> +    }
Отсутствуют тесты на:
1. testName
2. @Parameters
3. retryAnalyzer
4. Double.NaN

2022-12-13 12:26 UTC, nmyshko commented on src/test/java/tests/CalculatorDivision.java
> +    public int divInt(int a, int b) {
исправлено

2022-12-20 15:46 UTC, wildpioneer commented
Проверено

2022-12-20 15:46 UTC, closed without merging